---

- name: Set R base packages list (Debian/Ubuntu)
  set_fact:
    # only list core packages here; packages for MPI and parallel
    # execution are installed in `rmpi.yml` using R's
    # `install.packages()` because the `r-cran-*` DEB packages in
    # Debian/Ubuntu may have a dependency on the OS-provided R package
    # (e.g., `r-api-3.4`) and be incompatible with the DEB packages
    # provided in the CRAN repositories.
    r_packages:
      - r-base
      - r-base-dev
      - r-recommended
      # dependency packages for Jupyter's IRkernel,
      # see: https://irkernel.github.io/installation/#source-panel
      - libzmq3-dev
      # more dependencies, as appear in R pkg compile logs
      - libssh2-1-dev
      - libxml2-dev
      # more dependency packages, notes from CSCS' workshop on Spark
      - libssl-dev
      - libcurl4-openssl-dev


- name: Set R repository params (Ubuntu)
  set_fact:
    r_packages_repo: 'deb {{r_cran_mirror_url}}/bin/linux/ubuntu {{ansible_distribution_release}}-cran35/'
    r_packages_keyserver: keyserver.ubuntu.com
    r_packages_signing_key: 'E298A3A825C0D65DFD57CBB651716619E084DAB9'
  when: is_ubuntu


- name: Set R repository params (Debian)
  set_fact:
    r_packages_repo: 'deb {{r_cran_mirror_url}}/bin/linux/debian {{ansible_distribution_release}}-cran35/'
    r_packages_keyserver: keys.gnupg.net
    r_packages_signing_key: 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'
  when: is_debian


- name: Add signing key for CRAN repository
  apt_key:
    keyserver: '{{r_packages_keyserver}}'
    id: '{{r_packages_signing_key}}'
  when: not use_proxy


# Ansible's `apt_key` module ignores proxy settings (see issue #31691)
# so we need to resort to manual invocation of the `apt-key adv` in
# order to add `--keyserver-options http-proxy=...`; see
# https://github.com/ansible/ansible/issues/31691#issuecomment-357068590
- name: Add signing key for CRAN repository (through proxy server)
  command: |
    apt-key adv --keyserver-options http-proxy={{ proxy_url }} --keyserver hkp://{{r_packages_keyserver}}:80 --recv {{r_packages_signing_key}}
  when: use_proxy


- name: add CRAN repository
  apt_repository:
    repo: '{{r_packages_repo}}'
    state: present
    update_cache: yes
